### PR TITLE
Fix support for VoiceState.getGuildId; closes #658

### LINKED ISSUE #658: VS.getGuildID throws NoSuchElementException
**To Reproduce:** Enter a vc before booting up your bot, run voicestate.getGuildId() after booting up bot (The error only occurs if you are in a vc BEFORE starting your bot)

**Expected Behavior:** The guild ID of the current voice channel should be return

**Actual Behavior:** A NoSuchElementException is thrown until you switch to a different voice channel

**Version:** 3.1.0-SNAPSHOT

**Other:** Quantic told me to open an issue here

### PR DESCRIPTION
**Pull request by JasonTheKitten**
**Description:** This PR wraps generated VoiceStateData objects created on a guild create event in such a way that said objects will contain the guild id from the primary event.

**Justification:** Getting the Guild ID from a pre-existing voice state no longer throws an exception. This pull request fixes #658

### CODE REVIEW

File: core/src/main/java/discord4j/core/event/dispatch/GuildDispatchHandlers.java [hunk 1]
```diff
@@ -163,6 +163,22 @@
...
+    			.channelId(voiceState.channelId())
+    			.userId(voiceState.userId())
+    			.member(voiceState.member())
+    			.sessionId(voiceState.sessionId())
+    			.deaf(voiceState.deaf())
+    			.mute(voiceState.mute())
+    			.selfDeaf(voiceState.selfDeaf())
+    			.selfMute(voiceState.selfMute())
+    			.selfStream(voiceState.selfStream())
+    			.suppress(voiceState.suppress())
```
Comment (Alex1304) [inline core/src/main/java/discord4j/core/event/dispatch/GuildDispatchHandlers.java:179]: Here you can use `.from(voiceState)` instead of copying all fields one by one, it saves a lot of lines of code and is less prone to oversights.

Overall I'd honestly say it's not bad for a first PR :+1: I'll let the D4J team give further review.
