### PR TITLE
Fix unsigned long printing in requests (#1119)

### LINKED ISSUE #1119: Unsigned Long handling in GatewayDiscordClient#getMessageById
**To Reproduce:** 
```
GatewayDiscordClient.getMessageById(Snowflake.of("10781908199467992071"), Snowflake.of("10781908199467992071"));
```

**Expected Behavior:** 
A 404 (because the message/channel are fake IDs) but a request made with the correct IDs
```
/channels/10781908199467992071/messages/10781908199467992071
```

**Actual Behavior:** 
```
discord4j.rest.http.client.ClientException: GET /channels/-7664835874241559545/messages/-7664835874241559545 returned 400 Bad Request with response {code=50035, message=Invalid Form Body, errors={message_id={_errors=[{code=NUMBER_TYPE_MIN, message=snowflake value should be greater than or equal to 0.}]}}}
```

**Version:** 
3.2.3

**Other:**

### PR DESCRIPTION
**Pull request by Gregory-Widmer**
**Description:** Handles long string conversion by overriding for some objects how they are converted to a String. I chose to create an utility function that use the instanceof operator to "override" manually how objects are converted to String.

Then, if the object provided is a Long, we use the `Long.printUnsignedLong(long)` method to convert it to a String.

**Justification:** Fixes #1119

### CODE REVIEW

File: rest/src/main/java/discord4j/rest/util/RouteUtils.java [hunk 1]
```diff
@@ -129,9 +146,9 @@ private static boolean isPathSegmentAllowed(int c) {
...
         // other permitted | : @
         return c >= 'a' && c <= 'z' || c >= 'A' && c <= 'Z' || c >= '0' && c <= '9'
-                || c == '-' || c == '.' || c == '_' || c == '~'
-                || c == '!' || c == '$' || c == '&' || c == '\'' || c == '(' || c == ')'
-                || c == '*' || c == '+' || c == ',' || c == ';' || c == '='
-                || c == ':' || c == '@';
+            || c == '-' || c == '.' || c == '_' || c == '~'
+            || c == '!' || c == '$' || c == '&' || c == '\'' || c == '(' || c == ')'
+            || c == '*' || c == '+' || c == ',' || c == ';' || c == '='
+            || c == ':' || c == '@';
```
Comment (Azn9) [inline rest/src/main/java/discord4j/rest/util/RouteUtils.java:152]:
```suggestion
                || c == '-' || c == '.' || c == '_' || c == '~'
                || c == '!' || c == '$' || c == '&' || c == '\'' || c == '(' || c == ')'
                || c == '*' || c == '+' || c == ',' || c == ';' || c == '='
                || c == ':' || c == '@';
```

**Review by Azn9 — APPROVED** [review]
Just revert this format change
